# CloudFormation template for AgentCore deployment
# This template can be used standalone or imported via CfnInclude

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stats Agent Team - AgentCore Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Deployment environment

  ResearchContainerImage:
    Type: String
    Default: ghcr.io/agentplexus/stats-agent-research:latest
    Description: Container image for research agent

  SynthesisContainerImage:
    Type: String
    Default: ghcr.io/agentplexus/stats-agent-synthesis:latest
    Description: Container image for synthesis agent

  VerificationContainerImage:
    Type: String
    Default: ghcr.io/agentplexus/stats-agent-verification:latest
    Description: Container image for verification agent

  OrchestrationContainerImage:
    Type: String
    Default: ghcr.io/agentplexus/stats-agent-orchestration-eino:latest
    Description: Container image for orchestration agent

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpc'
        - Key: Environment
          Value: !Ref Environment

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-igw'

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-1'

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-private-1'

  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for AgentCore agents
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: '-1'
          SourceSecurityGroupId: !Ref SecurityGroup
          Description: Allow communication between agents
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-sg'

  # IAM Role
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - bedrock.amazonaws.com
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AgentCorePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: 'arn:aws:bedrock:*:*:foundation-model/*'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-execution-role'

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/agentcore/${AWS::StackName}'
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-logs'

Outputs:
  VPCID:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPCID'

  SecurityGroupID:
    Description: Security Group ID
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupID'

  ExecutionRoleARN:
    Description: IAM Execution Role ARN
    Value: !GetAtt ExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ExecutionRoleARN'

  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref LogGroup

  ResearchImage:
    Description: Research agent container image
    Value: !Ref ResearchContainerImage

  SynthesisImage:
    Description: Synthesis agent container image
    Value: !Ref SynthesisContainerImage

  VerificationImage:
    Description: Verification agent container image
    Value: !Ref VerificationContainerImage

  OrchestrationImage:
    Description: Orchestration agent container image
    Value: !Ref OrchestrationContainerImage
